let listaDiscos = [
    {
        id: 1,
        nombreArtista: "Amy Winehouse",
        tituloDisco: "Back to black",
        añoLanzamiento: "2006",
        precio: "20€",
        image: scr = "images/Amy Winehouse.jpg" ,
        cantidad: 1,
        },
    {
        id: 2,
        nombreArtista: "Joaquin Sabina",
        tituloDisco: "19 días y 500 noches",
        añoLanzamiento: "1999",
        precio: "15€",
        image: scr = "images/Joaquin Sabina.jpg",
        cantidad: 1,
        },
    {
        id: 3,
        nombreArtista: "Kiss",
        tituloDisco: "Dynasty",
        añoLanzamiento: "1979",
        precio: "17€",
        image: scr = "images/dynasty-kiss.jpg",
        cantidad: 1,
        },
    {
        id: 4,
        nombreArtista: "Oasis",
        tituloDisco: "Wanderwall",
        añoLanzamiento: "1995",
        precio: "18€",
        image: scr = "images/oasis.jpg",
        cantidad: 1,
        },
    {
        id: 5,
        nombreArtista: "Queen",
        tituloDisco: "Greatest Hits",
        añoLanzamiento: "1981",
        precio: "20€",
        image: scr = "images/queen.jpg",
        cantidad: 1,
        },           
    {
        id: 6,
        nombreArtista: "ACDC",
        tituloDisco: "For those about to rock",
        añoLanzamiento: "1981",
        precio: "20€",
        image: scr = "images/acdc.jpg",
        cantidad: 1,
        },
    ];

